In [3]:
import numpy as np
import pandas as pd

In [4]:
import os

In [5]:
os.chdir("C:/Users/Laven/Documents/Data_Analysis/Final_Project_Tableau")

In [6]:
df = pd.read_csv('TB_Burden_Country3.csv')

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AF,AFG,4,Middle East,1990,11731193,306.0,156.0,506.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AF,AFG,4,Middle East,1991,12612043,343.0,178.0,562.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AF,AFG,4,Middle East,1992,13811876,371.0,189.0,614.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,Middle East,1993,15175325,392.0,194.0,657.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,Middle East,1994,16485018,410.0,198.0,697.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZW,ZWE,716,Africa,2009,12888918,449.0,258.0,692.0,...,511.00,460.00,566.00,66000.0,59000.0,73000.0,NaN,50.0,45.0,54.0
5116,Zimbabwe,ZW,ZWE,716,Africa,2010,13076978,415.0,239.0,639.0,...,487.00,433.00,545.00,64000.0,57000.0,71000.0,NaN,53.0,48.0,59.0
5117,Zimbabwe,ZW,ZWE,716,Africa,2011,13358738,417.0,241.0,639.0,...,448.00,403.00,502.00,60000.0,54000.0,67000.0,NaN,48.0,43.0,53.0
5118,Zimbabwe,ZW,ZWE,716,Africa,2012,13724317,425.0,245.0,654.0,...,411.00,362.00,471.00,56000.0,50000.0,65000.0,NaN,45.0,40.0,52.0
5119,Zimbabwe,ZW,ZWE,716,Africa,2013,14149648,409.0,235.0,630.0,...,395.00,341.00,464.00,56000.0,48000.0,66000.0,NaN,42.0,36.0,49.0

In [7]:
df2 = df[(df['Region'] == 'Africa') | (df['Region'] == 'Middle East')]

In [8]:
df2

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AF,AFG,4,Middle East,1990,11731193,306.0,156.0,506.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AF,AFG,4,Middle East,1991,12612043,343.0,178.0,562.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AF,AFG,4,Middle East,1992,13811876,371.0,189.0,614.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,Middle East,1993,15175325,392.0,194.0,657.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,Middle East,1994,16485018,410.0,198.0,697.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZW,ZWE,716,Africa,2009,12888918,449.0,258.0,692.0,...,511.00,460.00,566.00,66000.0,59000.0,73000.0,NaN,50.0,45.0,54.0
5116,Zimbabwe,ZW,ZWE,716,Africa,2010,13076978,415.0,239.0,639.0,...,487.00,433.00,545.00,64000.0,57000.0,71000.0,NaN,53.0,48.0,59.0
5117,Zimbabwe,ZW,ZWE,716,Africa,2011,13358738,417.0,241.0,639.0,...,448.00,403.00,502.00,60000.0,54000.0,67000.0,NaN,48.0,43.0,53.0
5118,Zimbabwe,ZW,ZWE,716,Africa,2012,13724317,425.0,245.0,654.0,...,411.00,362.00,471.00,56000.0,50000.0,65000.0,NaN,45.0,40.0,52.0
5119,Zimbabwe,ZW,ZWE,716,Africa,2013,14149648,409.0,235.0,630.0,...,395.00,341.00,464.00,56000.0,48000.0,66000.0,NaN,42.0,36.0,49.0

In [44]:
df3 = df2[df2["Year"] == 2013]

In [54]:
df3.head(65)

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
23,Afghanistan,AF,AFG,4,Middle East,2013,30551674,340.0,178.0,554.0,...,0.64,0.57,0.72,200.0,170.0,220.0,NaN,53.0,47.0,60.0
71,Algeria,DZ,DZA,12,Africa,2013,39208194,126.0,64.0,209.0,...,0.30,0.29,2.60,120.0,110.0,1000.0,NaN,66.0,54.0,79.0
143,Angola,AO,AGO,24,Africa,2013,21471618,423.0,209.0,711.0,...,35.00,31.00,39.00,7500.0,6700.0,8300.0,NaN,85.0,77.0,95.0
383,Bahrain,BH,BHR,48,Middle East,2013,1332171,26.0,12.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,77.0,99.0
527,Benin,BJ,BEN,204,Africa,2013,10323474,105.0,56.0,168.0,...,11.00,9.60,12.00,1100.0,990.0,1300.0,NaN,54.0,48.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4519,Togo,TG,TGO,768,Africa,2013,6816982,104.0,56.0,166.0,...,16.00,14.00,18.00,1100.0,960.0,1200.0,NaN,52.0,47.0,59.0
4615,Tunisia,TN,TUN,788,Middle East,2013,10996515,38.0,14.0,73.0,...,0.14,0.12,0.15,15.0,13.0,16.0,NaN,87.0,81.0,96.0
4735,Uganda,UG,UGA,800,Africa,2013,37578876,154.0,85.0,243.0,...,86.00,77.00,102.00,32000.0,29000.0,38000.0,NaN,73.0,63.0,81.0
4783,United Arab Emirates,AE,ARE,784,Middle East,2013,9346129,2.7,1.3,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,38.0,69.0
4831,United Republic of Tanzania,TZ,TZA,834,Africa,2013,49253126,172.0,92.0,277.0,...,61.00,58.00,63.00,30000.0,29000.0,31000.0,NaN,79.0,77.0,83.0

In [9]:
# List of countries to update
countries_to_update = ["Egypt", "Djibouti", "Libya", "Morocco", "Sudan", "Somalia", "Tunisia"]

In [10]:
# Update the 'Region' for the specified countries
df2.loc[df2['Country or territory name'].isin(countries_to_update), 'Region'] = 'Africa'

In [11]:
df2

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AF,AFG,4,Middle East,1990,11731193,306.0,156.0,506.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AF,AFG,4,Middle East,1991,12612043,343.0,178.0,562.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AF,AFG,4,Middle East,1992,13811876,371.0,189.0,614.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,Middle East,1993,15175325,392.0,194.0,657.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,Middle East,1994,16485018,410.0,198.0,697.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZW,ZWE,716,Africa,2009,12888918,449.0,258.0,692.0,...,511.00,460.00,566.00,66000.0,59000.0,73000.0,NaN,50.0,45.0,54.0
5116,Zimbabwe,ZW,ZWE,716,Africa,2010,13076978,415.0,239.0,639.0,...,487.00,433.00,545.00,64000.0,57000.0,71000.0,NaN,53.0,48.0,59.0
5117,Zimbabwe,ZW,ZWE,716,Africa,2011,13358738,417.0,241.0,639.0,...,448.00,403.00,502.00,60000.0,54000.0,67000.0,NaN,48.0,43.0,53.0
5118,Zimbabwe,ZW,ZWE,716,Africa,2012,13724317,425.0,245.0,654.0,...,411.00,362.00,471.00,56000.0,50000.0,65000.0,NaN,45.0,40.0,52.0
5119,Zimbabwe,ZW,ZWE,716,Africa,2013,14149648,409.0,235.0,630.0,...,395.00,341.00,464.00,56000.0,48000.0,66000.0,NaN,42.0,36.0,49.0

In [12]:
# Filter the DataFrame for rows where the Region is 'Africa'
africa_df = df[df['Region'] == 'Africa']

In [13]:
africa_df.head(25)

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
48,Algeria,DZ,DZA,12,Africa,1990,26239708,100.0,51.0,166.0,...,0.04,0.03,0.23,11.0,9.0,61.0,NaN,69.0,58.0,83.0
49,Algeria,DZ,DZA,12,Africa,1991,26893663,99.0,51.0,164.0,...,0.05,0.04,0.27,13.0,12.0,73.0,NaN,66.0,57.0,74.0
50,Algeria,DZ,DZA,12,Africa,1992,27535151,100.0,51.0,165.0,...,0.06,0.05,0.32,16.0,15.0,89.0,NaN,64.0,56.0,71.0
51,Algeria,DZ,DZA,12,Africa,1993,28157560,102.0,52.0,170.0,...,0.07,0.07,0.39,19.0,18.0,110.0,NaN,71.0,63.0,80.0
52,Algeria,DZ,DZA,12,Africa,1994,28752749,106.0,54.0,176.0,...,0.08,0.08,0.50,24.0,23.0,140.0,NaN,67.0,58.0,77.0
53,Algeria,DZ,DZA,12,Africa,1995,29315463,110.0,56.0,182.0,...,0.10,0.09,0.60,29.0,27.0,180.0,NaN,65.0,56.0,74.0
54,Algeria,DZ,DZA,12,Africa,1996,29845208,114.0,59.0,189.0,...,0.12,0.11,0.72,34.0,33.0,210.0,NaN,70.0,60.0,80.0
55,Algeria,DZ,DZA,12,Africa,1997,30345466,119.0,61.0,195.0,...,0.13,0.13,0.82,40.0,38.0,250.0,NaN,71.0,64.0,81.0
56,Algeria,DZ,DZA,12,Africa,1998,30820435,122.0,62.0,201.0,...,0.15,0.15,0.93,46.0,45.0,290.0,NaN,63.0,58.0,72.0
57,Algeria,DZ,DZA,12,Africa,1999,31276295,126.0,64.0,207.0,...,0.17,0.16,1.10,53.0,51.0,350.0,NaN,66.0,59.0,75.0
58,Algeria,DZ,DZA,12,Africa,2000,31719449,129.0,66.0,213.0,...,0.19,0.18,1.20,59.0,56.0,390.0,NaN,70.0,64.0,81.0
59,Algeria,DZ,DZA,12,Africa,2001,32150198,132.0,67.0,217.0,...,0.20,0.19,1.40,65.0,61.0,440.0,NaN,67.0,62.0,76.0
60,Algeria,DZ,DZA,12,Africa,2002,32572977,134.0,69.0,221.0,...,0.22,0.20,1.50,71.0,66.0,480.0,NaN,67.0,62.0,75.0
61,Algeria,DZ,DZA,12,Africa,2003,33003442,136.0,70.0,224.0,...,0.23,0.22,1.60,77.0,71.0,540.0,NaN,68.0,62.0,75.0
62,Algeria,DZ,DZA,12,Africa,2004,33461345,138.0,71.0,227.0,...,0.25,0.23,1.80,82.0,76.0,610.0,NaN,67.0,59.0,74.0
63,Algeria,DZ,DZA,12,Africa,2005,33960903,139.0,71.0,229.0,...,0.26,0.24,2.00,87.0,82.0,670.0,NaN,70.0,63.0,78.0
64,Algeria,DZ,DZA,12,Africa,2006,34507214,139.0,71.0,230.0,...,0.27,0.25,2.00,92.0,87.0,680.0,NaN,68.0,62.0,75.0
65,Algeria,DZ,DZA,12,Africa,2007,35097043,140.0,71.0,231.0,...,0.27,0.26,2.00,95.0,90.0,690.0,NaN,68.0,62.0,75.0
66,Algeria,DZ,DZA,12,Africa,2008,35725377,139.0,71.0,229.0,...,0.28,0.27,2.00,99.0,95.0,730.0,NaN,64.0,58.0,71.0
67,Algeria,DZ,DZA,12,Africa,2009,36383302,138.0,71.0,227.0,...,0.29,0.28,2.20,100.0,100.0,800.0,NaN,67.0,61.0,75.0
68,Algeria,DZ,DZA,12,Africa,2010,37062820,136.0,70.0,224.0,...,0.29,0.29,2.30,110.0,110.0,850.0,NaN,69.0,62.0,78.0
69,Algeria,DZ,DZA,12,Africa,2011,37762962,132.0,68.0,219.0,...,0.30,0.29,2.40,110.0,110.0,900.0,NaN,67.0,59.0,76.0
70,Algeria,DZ,DZA,12,Africa,2012,38481705,129.0,66.0,214.0,...,0.30,0.28,2.50,120.0,110.0,970.0,NaN,68.0,59.0,80.0
71,Algeria,DZ,DZA,12,Africa,2013,39208194,126.0,64.0,209.0,...,0.30,0.29,2.60,120.0,110.0,1000.0,NaN,66.0,54.0,79.0
120,Angola,AO,AGO,24,Africa,1990,10333844,365.0,185.0,606.0,...,1.70,0.93,1.90,180.0,96.0,200.0,NaN,48.0,37.0,59.0

In [14]:
# List of countries to exclude
exclude_countries = ["Morocco", "Algeria", "Tunisia", "Libya", "Egypt"]

# Create a new DataFrame excluding the specified countries
subsaharan_africa_df = africa_df[~africa_df['Country or territory name'].isin(exclude_countries)]

In [15]:
subsaharan_africa_df

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
120,Angola,AO,AGO,24,Africa,1990,10333844,365.0,185.0,606.0,...,1.7,0.93,1.9,180.0,96.0,200.0,NaN,48.0,37.0,59.0
121,Angola,AO,AGO,24,Africa,1991,10652727,387.0,198.0,639.0,...,2.8,1.70,3.1,300.0,180.0,330.0,NaN,50.0,41.0,58.0
122,Angola,AO,AGO,24,Africa,1992,11002758,406.0,207.0,671.0,...,4.2,2.70,4.6,460.0,290.0,510.0,NaN,48.0,41.0,55.0
123,Angola,AO,AGO,24,Africa,1993,11372156,420.0,214.0,694.0,...,5.9,3.90,6.6,670.0,450.0,750.0,NaN,33.0,30.0,37.0
124,Angola,AO,AGO,24,Africa,1994,11743432,430.0,218.0,712.0,...,7.8,5.60,8.8,920.0,650.0,1000.0,NaN,27.0,25.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZW,ZWE,716,Africa,2009,12888918,449.0,258.0,692.0,...,511.0,460.00,566.0,66000.0,59000.0,73000.0,NaN,50.0,45.0,54.0
5116,Zimbabwe,ZW,ZWE,716,Africa,2010,13076978,415.0,239.0,639.0,...,487.0,433.00,545.0,64000.0,57000.0,71000.0,NaN,53.0,48.0,59.0
5117,Zimbabwe,ZW,ZWE,716,Africa,2011,13358738,417.0,241.0,639.0,...,448.0,403.00,502.0,60000.0,54000.0,67000.0,NaN,48.0,43.0,53.0
5118,Zimbabwe,ZW,ZWE,716,Africa,2012,13724317,425.0,245.0,654.0,...,411.0,362.00,471.0,56000.0,50000.0,65000.0,NaN,45.0,40.0,52.0
5119,Zimbabwe,ZW,ZWE,716,Africa,2013,14149648,409.0,235.0,630.0,...,395.0,341.00,464.0,56000.0,48000.0,66000.0,NaN,42.0,36.0,49.0

In [16]:
# Group by 'Year' and calculate the total population for each year
africa_yearly_population = africa_df.groupby('Year')['Estimated total population number'].sum()

In [23]:
# Group by 'Year' and calculate the total population for each year
subsaharan_africa_yearly_population = subsaharan_africa_df.groupby('Year')['Estimated total population number'].sum()

In [17]:
metric_name1 = 'Estimated prevalence of TB (all forms) per 100 000 population'
africa_yearly_weighted_metric = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name1] * x['Estimated total population number']).sum())
metric_name2 = 'Estimated prevalence of TB (all forms) per 100 000 population, low bound'
africa_yearly_weighted_metric2 = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name2] * x['Estimated total population number']).sum())
metric_name3 = 'Estimated prevalence of TB (all forms) per 100 000 population, high bound'
africa_yearly_weighted_metric3 = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name3] * x['Estimated total population number']).sum())
metric_name4 = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000'
africa_yearly_weighted_metric4 = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name4] * x['Estimated total population number']).sum())
metric_name5 = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound'
africa_yearly_weighted_metric5 = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name5] * x['Estimated total population number']).sum())
metric_name6 = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound'
africa_yearly_weighted_metric6 = africa_df.groupby('Year').apply(
    lambda x: (x[metric_name6] * x['Estimated total population number']).sum())

In [18]:
africa_yearly_weighted_average_1 = africa_yearly_weighted_metric / africa_yearly_population
africa_yearly_weighted_average_2 = africa_yearly_weighted_metric2 / africa_yearly_population
africa_yearly_weighted_average_3 = africa_yearly_weighted_metric3 / africa_yearly_population
africa_yearly_weighted_average_4 = africa_yearly_weighted_metric4 / africa_yearly_population
africa_yearly_weighted_average_5 = africa_yearly_weighted_metric5 / africa_yearly_population
africa_yearly_weighted_average_6 = africa_yearly_weighted_metric6 / africa_yearly_population

In [19]:
# Combine into a DataFrame
aggregated_africa_df = pd.DataFrame({
    'Total Population': africa_yearly_population,
    'Estimated prevalence of TB (all forms) per 100 000 population': africa_yearly_weighted_average_1,
    'Estimated prevalence of TB (all forms) per 100 000 population, low bound': africa_yearly_weighted_average_2,
    'Estimated prevalence of TB (all forms) per 100 000 population, high bound': africa_yearly_weighted_average_3,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000': africa_yearly_weighted_average_4,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound': africa_yearly_weighted_average_5,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound': africa_yearly_weighted_average_6
})

In [20]:
aggregated_africa_df

,Total Population,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound"
Year,,,,,,,
1990,502970338,408.784537,218.348410,663.512020,95.018347,57.272956,135.983566
1991,517234627,403.713662,222.395787,643.671960,97.346943,63.954508,132.963797
1992,531812865,399.680474,223.399364,631.958662,100.337757,68.310282,132.659145
1993,546641498,396.465307,223.345361,624.010018,102.753286,71.417253,134.458380
1994,561636401,394.822668,222.651078,620.637715,106.828564,72.292145,141.113165
1995,576744821,394.005368,222.621992,618.650452,109.218874,74.523168,145.293736
1996,591951348,393.989357,224.302208,615.897678,111.463197,77.802629,146.424635
1997,607297345,394.531068,227.388147,611.899237,115.674011,82.137591,146.600213
1998,622859385,393.980658,229.185626,607.416081,117.255631,84.667248,148.639119
1999,638744959,391.480143,229.048600,601.433986,118.522454,83.085478,154.326165
2000,655041871,387.862448,228.591199,592.958148,120.694788,81.958974,158.970418
2001,671776860,383.399179,227.298223,583.518590,120.081004,82.447749,156.658239
2002,688959998,378.007631,225.368800,573.392320,118.490130,82.178330,151.312167
2003,706642674,371.524686,222.255111,562.832574,115.911284,80.220873,146.388074
2004,724879500,365.536102,219.049024,552.948707,111.734792,77.159197,144.257687
2005,743711558,359.961060,215.856933,544.065044,108.122738,72.464465,140.312072
2006,763161061,352.385942,211.988529,532.135343,102.755675,69.956845,133.231064
2007,783231097,344.035323,207.654998,518.391268,97.097026,67.389638,126.069318
2008,803916077,334.720588,202.220992,504.035407,91.714561,63.612946,121.472891
2009,825199127,324.666467,196.262136,488.682155,87.820876,59.440538,117.259588
2010,847062195,315.011946,190.290561,474.141633,83.935985,55.821033,114.898293
2011,879889810,308.619159,185.953977,465.413911,79.324137,52.402915,111.096979
2012,903366645,305.871866,183.517575,462.440177,76.532713,46.588809,107.844584
2013,927370706,303.085086,181.208163,459.460675,73.761592,42.034777,109.988109

In [21]:
# Assuming aggregated_africa_df is your DataFrame
aggregated_africa_df.to_csv('aggregated_africa_df.csv', index=True)

In [22]:
metric_name1b = 'Estimated prevalence of TB (all forms) per 100 000 population'
subsaharan_africa_yearly_weighted_metric = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name1] * x['Estimated total population number']).sum())
metric_name2b = 'Estimated prevalence of TB (all forms) per 100 000 population, low bound'
subsaharan_africa_yearly_weighted_metric2 = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name2] * x['Estimated total population number']).sum())
metric_name3b = 'Estimated prevalence of TB (all forms) per 100 000 population, high bound'
subsaharan_africa_yearly_weighted_metric3 = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name3] * x['Estimated total population number']).sum())
metric_name4b = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000'
subsaharan_africa_yearly_weighted_metric4 = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name4] * x['Estimated total population number']).sum())
metric_name5b = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound'
subsaharan_africa_yearly_weighted_metric5 = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name5] * x['Estimated total population number']).sum())
metric_name6b = 'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound'
subsahran_africa_yearly_weighted_metric6 = subsaharan_africa_df.groupby('Year').apply(
    lambda x: (x[metric_name6] * x['Estimated total population number']).sum())

In [24]:
subsaharan_africa_yearly_weighted_average_1 = subsaharan_africa_yearly_weighted_metric / subsaharan_africa_yearly_population
subsaharan_africa_yearly_weighted_average_2 = subsaharan_africa_yearly_weighted_metric2 / subsaharan_africa_yearly_population
subsaharan_africa_yearly_weighted_average_3 = subsaharan_africa_yearly_weighted_metric3 / subsaharan_africa_yearly_population
subsaharan_africa_yearly_weighted_average_4 = subsaharan_africa_yearly_weighted_metric4 / subsaharan_africa_yearly_population
subsaharan_africa_yearly_weighted_average_5 = subsaharan_africa_yearly_weighted_metric5 / subsaharan_africa_yearly_population
subsaharan_africa_yearly_weighted_average_6 = subsahran_africa_yearly_weighted_metric6 / subsaharan_africa_yearly_population

In [25]:
# Combine into a DataFrame
aggregated_subsaharan_africa_df = pd.DataFrame({
    'Total Population': subsaharan_africa_yearly_population,
    'Estimated prevalence of TB (all forms) per 100 000 population': subsaharan_africa_yearly_weighted_average_1,
    'Estimated prevalence of TB (all forms) per 100 000 population, low bound': subsaharan_africa_yearly_weighted_average_2,
    'Estimated prevalence of TB (all forms) per 100 000 population, high bound': subsaharan_africa_yearly_weighted_average_3,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000': subsaharan_africa_yearly_weighted_average_4,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound': subsaharan_africa_yearly_weighted_average_5,
    'Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound': subsaharan_africa_yearly_weighted_average_6
})

In [26]:
aggregated_subsaharan_africa_df

,Total Population,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, low bound","Estimated Mortality From TB In People (HIV+ or HIV-), per 100,000, high bound"
Year,,,,,,,
1990,476730630,425.780333,227.559426,690.895556,99.660284,60.110671,142.604431
1991,490340964,420.426251,231.796308,669.980462,102.134665,67.115514,139.436402
1992,504277714,416.043972,232.812912,657.456075,105.260273,71.683291,139.124609
1993,518483938,412.456978,232.650697,648.666162,107.773078,74.929291,140.982824
1994,532883652,410.406643,231.750967,644.628987,112.009647,75.836254,147.875225
1995,547429358,409.214178,231.544789,642.033578,114.463207,78.130357,152.188604
1996,562106140,408.855482,233.078983,638.563949,116.756757,81.506617,153.334849
1997,576951879,409.022950,236.139528,633.826545,121.114468,86.024401,153.484759
1998,592038950,408.139460,237.888996,628.573338,122.698464,88.652596,155.484990
1999,607468664,405.148725,237.546336,621.741920,123.947002,86.935233,161.349985
2000,623322422,401.035364,236.865093,612.293347,126.159813,85.696516,166.110309
2001,639626662,396.035509,235.355453,601.941282,125.441363,86.169782,163.589772
2002,656387021,390.116425,233.128547,590.879666,123.681239,85.845058,157.900791
2003,673639232,383.063690,229.714508,579.432915,120.903677,83.750306,152.647077
2004,691418155,376.547766,226.213891,568.723072,116.458701,80.502833,150.332240
2005,709750655,370.533840,222.788201,559.140611,112.616212,75.551406,146.083289
2006,728653847,362.491363,218.665391,546.443714,106.945473,72.858107,138.608697
2007,748134054,353.607186,214.065863,531.873590,100.979911,70.136708,131.022521
2008,768190700,343.822745,208.323538,516.826168,95.311893,66.154758,126.157489
2009,788815825,333.276262,202.039720,500.751970,91.208249,61.776499,121.702059
2010,809999375,323.202925,195.794649,485.587264,87.130561,58.004844,119.200092
2011,842126848,316.539180,191.243313,476.463694,82.259579,54.384670,115.109856
2012,864884940,313.741503,188.746336,473.494135,79.344196,48.361087,111.709888
2013,888162512,310.902559,186.382352,470.517335,76.439660,43.642712,113.864015

In [28]:
# Assuming subsaharan_aggregated_africa_df is your DataFrame
aggregated_subsaharan_africa_df.to_csv('aggregated_subsaharan_africa_df.csv', index=True)